<?php
$root = dirname(__DIR__);
chdir($root.'/bootrap');
session_id('giaoviec-create-form-smoke');
session_start();
$_SESSION['login_id'] = 1;
$_SESSION['membername'] = 'Administrator';
$_SESSION['loginname'] = 'administrator';
$_REQUEST = array('mode' => 'info', 'member_id' => 34, 'month' => '07', 'year' => '2026', 'day' => '2026-07-31', 'view' => 'day');
require 'common.php';
$skin = 'default';
$langpath = 'vietnam';
ob_start();
require 'modules/common_lists/giaoviec.php';
$html = ob_get_clean();
if (!preg_match('/name="id" value="0"/', $html)) throw new RuntimeException('New-task form must submit id=0.');
if (!preg_match('/name="member_id1" value="34"/', $html)) throw new RuntimeException('New-task form must retain the selected employee.');
if (!preg_match('/<option[^>]*value="34"[^>]*selected/', $html)) throw new RuntimeException('Selected employee must be rendered server-side.');
if (!preg_match('/name="ngay"[^>]*value="2026-07-31"/', $html)) throw new RuntimeException('New-task form must default to the viewed date.');
echo "Task create form smoke OK\n";
